(()=>{
const c=document.getElementById('game'),ctx=c.getContext('2d'),app=document.getElementById('app');
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const launch=new URLSearchParams(location.search).get('launch');
const SCORE_API='https://blockrush-backend.vercel.app/api/score';
const RUN_KEY='ballsrushActiveRun';
let W=390,H=844,dpr=1,last=0,run=false,paused=false,level=1,score=0,coins=0,gems=0,lives=5,camX=0,levelStartScore=0;
let checkpoint={score:0,coins:0,gems:0,lives:5};
let touch={active:false,dir:0,started:0,pointerId:null};
let player={x:80,y:0,vx:0,vy:0,r:18,onGround:false,canJump:true};
let world={len:1800,name:'Warm Up'},platforms=[],spikes=[],springs=[],collectibles=[],portals=[],goals=[],particles=[],saws=[],moving=[],chase=null;
let profile;try{profile=JSON.parse(localStorage.getItem('ballsrushProfile')||'null')}catch(e){};profile=profile&&typeof profile==='object'?profile:{bestScore:0,bestLevel:1,totalCoins:0,totalGems:0};
profile.bestScore=Number(profile.bestScore)||0;profile.bestLevel=Math.max(1,Number(profile.bestLevel)||1);profile.totalCoins=Number(profile.totalCoins)||0;profile.totalGems=Number(profile.totalGems)||0;
let activeRun=null;try{activeRun=JSON.parse(localStorage.getItem(RUN_KEY)||'null')}catch(e){};
if(activeRun&&typeof activeRun==='object')activeRun={active:true,level:Math.max(1,Number(activeRun.level)||1),score:Math.max(0,Number(activeRun.score)||0),coins:Math.max(0,Number(activeRun.coins)||0),gems:Math.max(0,Number(activeRun.gems)||0),lives:clamp(Number(activeRun.lives)||5,1,5)};else activeRun=null;
function saveProfile(){profile.bestScore=Math.max(profile.bestScore,Math.floor(score));profile.bestLevel=Math.max(profile.bestLevel,level);localStorage.setItem('ballsrushProfile',JSON.stringify(profile));renderHome()}
function saveActive(nextLevel=level){activeRun={active:true,level:Math.max(1,nextLevel),score:Math.floor(Math.max(0,score)),coins:Math.max(0,coins),gems:Math.max(0,gems),lives:clamp(lives,1,5)};localStorage.setItem(RUN_KEY,JSON.stringify(activeRun))}
function clearActive(){activeRun=null;localStorage.removeItem(RUN_KEY)}
function resize(){const r=app.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);c.width=r.width*dpr;c.height=r.height*dpr;W=r.width;H=r.height;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function rng(seed){let s=(seed*9301+49297)%233280;return()=>{s=(s*9301+49297)%233280;return s/233280}}
function challengeName(n){if(n%10===0)return'CHASE RUN';if(n%7===0)return'SKY RUN';if(n%5===0)return'SPIKE GAUNTLET';if(n%3===0)return'MOVING MAYHEM';return n<3?'WARM UP':'RUSH COURSE'}
function generateLevel(n){const R=rng(n*7919+17),diff=Math.min(1,(n-1)/28),len=Math.floor(1750+Math.min(3600,n*105));world={len,name:challengeName(n)};platforms=[];spikes=[];springs=[];collectibles=[];portals=[];goals=[];particles=[];saws=[];moving=[];chase=null;
 const sky=n%7===0,gaunt=n%5===0,chaseRun=n%10===0,movingRush=n%3===0;
 let x=0,y=560;platforms.push({x:0,y:560,w:260,h:100,ground:true});x=260;
 while(x<len-300){let gap=Math.floor(58+R()*(62+diff*78)+(sky?30:0)),w=Math.floor(155+R()*(175-diff*55));x+=gap;y=clamp(560+(R()-.5)*(sky?165:95),400,585);platforms.push({x,y,w,h:100,ground:true});
   if(R()<.60){const pw=Math.floor(82+R()*80),py=y-95-R()*145;platforms.push({x:x+18+R()*Math.max(1,w-pw-28),y:py,w:pw,h:24,ground:false});}
   if(R()<.34+diff*.30){const sx=x+26+R()*Math.max(18,w-75);spikes.push({x:sx,y:y,w:40+R()*52});}
   if(R()<.26){springs.push({x:x+20+R()*Math.max(20,w-60),y:y-28,w:36,h:28});}
   if((movingRush||n>7)&&R()<.20+diff*.23){moving.push({x:x+w*.5,y:y-120-R()*95,w:88,h:18,baseY:y-120-R()*95,phase:R()*6.28,amp:40+R()*60,speed:.9+R()*1.5});}
   if((gaunt||n>4)&&R()<.20+diff*.35){saws.push({x:x+w*.5,y:y-45-R()*95,r:16+R()*9,baseY:y-45-R()*95,phase:R()*6.28,amp:30+R()*60,speed:1.05+R()*1.7});}
   if(R()<.76){const count=1+(R()>.52?1:0);for(let k=0;k<count;k++)collectibles.push({x:x+32+k*38,y:y-55-(k%2)*25,r:10,type:R()<.24?'gem':'coin',taken:false});}
   x+=w;
 }
 platforms.push({x:len-280,y:540,w:280,h:120,ground:true});
 if(n>3&&n%4===0)portals.push({x:Math.floor(len*.38),y:470,r:25,toX:Math.floor(len*.62),toY:440,cool:0});
 if(chaseRun)chase={x:-120,speed:76+Math.min(105,n*3.5)};
 goals=[{x:len-85,y:485,r:31}];
}
function buildLevel(n,preserve=true){level=n;generateLevel(n);player={x:80,y:502,vx:0,vy:0,r:18,onGround:false,canJump:true};camX=0;touch.active=false;touch.dir=0;if(!preserve){score=0;coins=0;gems=0;lives=5}levelStartScore=score;checkpoint={score,coins,gems,lives};saveActive(level);updateHud()}
function updateHud(){$('score').textContent=String(Math.floor(score)).padStart(6,'0');$('coins').textContent=coins;$('gems').textContent=gems;$('lives').textContent='❤️'.repeat(lives)+'🖤'.repeat(Math.max(0,5-lives));$('levelNow').textContent=level;$('levelNext').textContent=level+1;$('levelFill').style.width=clamp(player.x/world.len*100,0,100)+'%'}
function enterLevel(n,preserve=true){buildLevel(n,preserve);run=true;paused=false;$('home').classList.add('hidden');$('levels').classList.add('hidden');$('pause').classList.add('hidden');$('result').classList.add('hidden');$('hud').classList.remove('hidden');last=performance.now()}
function newRun(n=1){clearActive();score=0;coins=0;gems=0;lives=5;enterLevel(n,true)}
function resumeRun(){if(!activeRun){newRun(1);return}score=activeRun.score;coins=activeRun.coins;gems=activeRun.gems;lives=activeRun.lives;enterLevel(activeRun.level,true)}
function goHome(){saveActive(level);syncScore(true);run=false;paused=false;touch.active=false;$('hud').classList.add('hidden');$('pause').classList.add('hidden');$('result').classList.add('hidden');$('home').classList.remove('hidden');saveProfile()}
function renderHome(){$('bestScore').textContent=profile.bestScore;$('bestLevel').textContent=profile.bestLevel;if($('playBtn'))$('playBtn').textContent=activeRun?`▶ CONTINUE LEVEL ${activeRun.level}`:'▶ START ENDLESS RUN';const grid=$('levelGrid');grid.innerHTML='';const maxShow=Math.max(12,Math.min(profile.bestLevel+2,40)),start=Math.max(1,maxShow-11);for(let i=start;i<=maxShow;i++){const b=document.createElement('button');b.textContent=i;b.disabled=i>profile.bestLevel;b.className=i<=profile.bestLevel?'unlocked':'locked';b.onclick=()=>newRun(i);grid.appendChild(b)}}
function circleRect(px,py,r,o){const nx=clamp(px,o.x,o.x+o.w),ny=clamp(py,o.y,o.y+o.h);return(px-nx)**2+(py-ny)**2<r*r}
function burst(x,y,col,n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*220,vy:(Math.random()-.5)*220,life:.55,col})}
function hurt(){lives--;score=Math.max(levelStartScore,score-180);if(lives<=0){lives=3;score=checkpoint.score;coins=checkpoint.coins;gems=checkpoint.gems;saveActive(level);finish(false);return}player.x=Math.max(65,camX+78);player.y=360;player.vx=0;player.vy=-220;if(chase)chase.x=Math.min(chase.x,player.x-260);burst(player.x,player.y,'#ff365b',16);saveActive(level);updateHud()}
function jump(){if(!run||paused)return;if(player.onGround||player.canJump){player.vy=-(440+Math.min(60,level*1.25));player.onGround=false;player.canJump=false;setTimeout(()=>player.canJump=true,135)}}
async function submitScore(v,keepalive=false){if(!launch)return null;try{const r=await fetch(SCORE_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({launch,score:Math.floor(Math.max(0,v))}),keepalive});return await r.json()}catch(e){return null}}
function syncScore(keepalive=false){profile.bestScore=Math.max(profile.bestScore,score);localStorage.setItem('ballsrushProfile',JSON.stringify(profile));if(score>0)submitScore(score,keepalive)}
function finish(win){if(!run)return;run=false;paused=false;touch.active=false;$('hud').classList.add('hidden');$('resultTitle').textContent=win?`${world.name} COMPLETE!`:'LEVEL FAILED — RUN SAVED';$('resultScore').textContent=Math.floor(score);$('resultCoins').textContent=coins;$('resultGems').textContent=gems;$('nextBtn').classList.toggle('hidden',!win);$('result').classList.remove('hidden');if(win){profile.bestLevel=Math.max(profile.bestLevel,level+1);profile.totalCoins+=Math.max(0,coins-checkpoint.coins);profile.totalGems+=Math.max(0,gems-checkpoint.gems);lives=Math.min(5,lives+1);saveActive(level+1);saveProfile();submitScore(score);try{if(window.TelegramGameProxy&&typeof TelegramGameProxy.shareScore==='function')TelegramGameProxy.shareScore()}catch(e){}}else{saveActive(level);saveProfile();submitScore(score)}}
function update(dt){if(!run||paused)return;let dir=touch.active?touch.dir:0,held=touch.active?(performance.now()-touch.started)/1000:0;const difficulty=Math.min(1,(level-1)/35),max=260+Math.min(190,held*150)+difficulty*45,accel=950+Math.min(1000,held*750);if(dir<0)player.vx-=accel*dt;if(dir>0)player.vx+=accel*dt;if(!dir)player.vx*=Math.pow(.82,dt*60);player.vx=clamp(player.vx,-max,max);player.vy+=1030*dt;player.vy=clamp(player.vy,-690,770);const oldY=player.y;player.x+=player.vx*dt;player.y+=player.vy*dt;player.onGround=false;
 for(const m of moving)m.y=m.baseY+Math.sin(performance.now()/1000*m.speed+m.phase)*m.amp;
 for(const s of saws)s.y=s.baseY+Math.sin(performance.now()/1000*s.speed+s.phase)*s.amp;
 const allPlatforms=platforms.concat(moving);for(const p of allPlatforms){if(circleRect(player.x,player.y,player.r,p)){if(player.vy>=0&&oldY+player.r<=p.y+10){player.y=p.y-player.r;player.vy=0;player.onGround=true}else if(player.vy<0&&oldY-player.r>=p.y+p.h-10){player.y=p.y+p.h+player.r;player.vy=0}else{if(player.x<p.x)player.x=p.x-player.r;else if(player.x>p.x+p.w)player.x=p.x+p.w+player.r;player.vx*=-.3}}}
 for(const s of springs){if(circleRect(player.x,player.y,player.r,s)&&player.vy>=0){player.y=s.y-player.r;player.vy=-660;score+=90;burst(s.x+s.w/2,s.y,'#4ce7ff',10)}}
 for(const sp of spikes){if(player.x+player.r>sp.x&&player.x-player.r<sp.x+sp.w&&player.y+player.r>sp.y-18&&player.y-player.r<sp.y+15){hurt();break}}
 for(const s of saws){if((player.x-s.x)**2+(player.y-s.y)**2<(player.r+s.r)**2){hurt();break}}
 for(const it of collectibles){if(!it.taken&&(player.x-it.x)**2+(player.y-it.y)**2<(player.r+it.r)**2){it.taken=true;if(it.type==='gem'){gems++;score+=300}else{coins++;score+=120}burst(it.x,it.y,it.type==='gem'?'#d45cff':'#ffd847',9)}}
 for(const po of portals){po.cool=Math.max(0,po.cool-dt);if(po.cool<=0&&(player.x-po.x)**2+(player.y-po.y)**2<(player.r+po.r)**2){player.x=po.toX;player.y=po.toY-40;player.vx=165;player.vy=-190;po.cool=1;score+=350}}
 if(chase){chase.x+=chase.speed*dt;if(player.x-chase.x>500)chase.x+=40*dt;if(player.x<chase.x+35){hurt();chase.x=player.x-280}}
 for(const g of goals){if((player.x-g.x)**2+(player.y-g.y)**2<(player.r+g.r)**2){score+=1000+level*75;finish(true);return}}
 if(player.y>H+120)hurt();camX=clamp(player.x-W*.35,0,Math.max(0,world.len-W));for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=260*dt;p.life-=dt;if(p.life<=0)particles.splice(i,1)}updateHud()}
function drawBlock(p,m=false){const x=p.x-camX,y=p.y;ctx.fillStyle=m?'#7c43e8':'#e5542e';ctx.fillRect(x,y,p.w,p.h);ctx.fillStyle=m?'#a66cff':'#ff7a36';for(let yy=y;yy<y+p.h;yy+=28)for(let xx=x;xx<x+p.w;xx+=48)ctx.fillRect(xx+2,yy+2,44,Math.min(24,p.h-4));ctx.fillStyle=m?'#55e8ff':'#64c83d';ctx.fillRect(x,y-6,p.w,10)}
function draw(){let g=ctx.createLinearGradient(0,0,0,H);const hue=(level*17)%360;g.addColorStop(0,`hsl(${(hue+195)%360} 90% 55%)`);g.addColorStop(.55,`hsl(${(hue+185)%360} 85% 72%)`);g.addColorStop(1,'#dff8ff');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.16;ctx.fillStyle='#1f865e';for(let i=0;i<9;i++){ctx.beginPath();ctx.arc((i*135-camX*.18)%(W+170),H-155-(i%3)*24,90,Math.PI,0);ctx.fill()}ctx.globalAlpha=1;platforms.forEach(p=>drawBlock(p,false));moving.forEach(p=>drawBlock(p,true));
 for(const sp of spikes){ctx.fillStyle='#d9e1e9';for(let xx=sp.x-camX;xx<sp.x+sp.w-camX;xx+=18){ctx.beginPath();ctx.moveTo(xx,sp.y);ctx.lineTo(xx+9,sp.y-22);ctx.lineTo(xx+18,sp.y);ctx.fill()}}
 for(const s of springs){const xx=s.x-camX;ctx.fillStyle='#ffe02f';ctx.fillRect(xx,s.y-8,s.w,10);ctx.strokeStyle='#5c432f';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(xx+8,s.y+10);ctx.lineTo(xx+28,s.y-2);ctx.lineTo(xx+8,s.y-14);ctx.stroke()}
 for(const s of saws){const xx=s.x-camX;ctx.save();ctx.translate(xx,s.y);ctx.rotate(performance.now()/260);ctx.fillStyle='#dce6ee';for(let i=0;i<8;i++){ctx.rotate(Math.PI/4);ctx.fillRect(-3,-s.r-8,6,12)}ctx.fillStyle='#5f6f83';ctx.beginPath();ctx.arc(0,0,s.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff365b';ctx.beginPath();ctx.arc(0,0,6,0,Math.PI*2);ctx.fill();ctx.restore()}
 for(const it of collectibles){if(it.taken)continue;const xx=it.x-camX;ctx.save();ctx.translate(xx,it.y);ctx.rotate(performance.now()/700);ctx.fillStyle=it.type==='gem'?'#d653ff':'#ffd335';ctx.beginPath();ctx.moveTo(0,-it.r);ctx.lineTo(it.r,0);ctx.lineTo(0,it.r);ctx.lineTo(-it.r,0);ctx.closePath();ctx.fill();ctx.restore()}
 for(const po of portals){const xx=po.x-camX;ctx.strokeStyle='#ffd83d';ctx.lineWidth=8;ctx.beginPath();ctx.arc(xx,po.y,po.r,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#35baff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(xx,po.y,po.r-8,0,Math.PI*2);ctx.stroke()}
 for(const gg of goals){const xx=gg.x-camX;ctx.strokeStyle='#7b50ff';ctx.lineWidth=9;ctx.beginPath();ctx.arc(xx,gg.y,gg.r,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#53e7ff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(xx,gg.y,gg.r-10,0,Math.PI*2);ctx.stroke()}
 if(chase){const xx=chase.x-camX;ctx.fillStyle='#ff234f';ctx.globalAlpha=.75;ctx.fillRect(xx-28,95,55,H-95);ctx.globalAlpha=1;ctx.fillStyle='#fff';ctx.font='900 12px system-ui';ctx.fillText('DANGER',xx-24,125)}
 for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.col;ctx.beginPath();ctx.arc(p.x-camX,p.y,3,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
 const px=player.x-camX,py=player.y;ctx.save();ctx.translate(px,py);ctx.fillStyle='#f5332f';ctx.shadowColor='#ff6a45';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(0,0,player.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-6,-5,5,0,Math.PI*2);ctx.arc(6,-5,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#222';ctx.beginPath();ctx.arc(-5,-4,2,0,Math.PI*2);ctx.arc(7,-4,2,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#7d1010';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,4,8,.15,Math.PI-.15);ctx.stroke();ctx.restore();
 if(run&&!paused){ctx.save();ctx.fillStyle='#083a75cc';ctx.font='900 12px system-ui';ctx.textAlign='center';ctx.fillText(`LEVEL ${level} · ${world.name}`,W/2,145);ctx.globalAlpha=.08;ctx.fillStyle='#fff';ctx.fillRect(0,H*.56,W/2,H*.44);ctx.fillRect(W/2,H*.56,W/2,H*.44);ctx.globalAlpha=.28;ctx.fillStyle='#063d80';ctx.font='900 13px system-ui';ctx.fillText('HOLD LEFT',W*.25,H-24);ctx.fillText('HOLD RIGHT',W*.75,H-24);ctx.restore()}}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function touchAction(e){if(!run||paused)return;e.preventDefault();const r=c.getBoundingClientRect(),xx=e.clientX-r.left,yy=e.clientY-r.top;if(yy<r.height*.48){touch.active=false;touch.dir=0;jump();return}touch.active=true;touch.pointerId=e.pointerId;touch.started=performance.now();touch.dir=xx<r.width/2?-1:1;try{c.setPointerCapture(e.pointerId)}catch(_){}}
c.addEventListener('pointerdown',touchAction,{passive:false});c.addEventListener('pointermove',e=>{if(!touch.active||e.pointerId!==touch.pointerId)return;e.preventDefault();const r=c.getBoundingClientRect(),xx=e.clientX-r.left,yy=e.clientY-r.top;if(yy<r.height*.48){touch.active=false;touch.dir=0;jump()}else touch.dir=xx<r.width/2?-1:1},{passive:false});function release(e){if(e.pointerId!=null&&touch.pointerId!==null&&e.pointerId!==touch.pointerId)return;touch.active=false;touch.dir=0;touch.pointerId=null}c.addEventListener('pointerup',release);c.addEventListener('pointercancel',release);c.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('selectstart',e=>e.preventDefault());
$('playBtn').onclick=()=>activeRun?resumeRun():newRun(1);$('levelsBtn').onclick=()=>{$('home').classList.add('hidden');$('levels').classList.remove('hidden');renderHome()};$('levelsBack').onclick=()=>{$('levels').classList.add('hidden');$('home').classList.remove('hidden')};$('pauseBtn').onclick=e=>{e.stopPropagation();if(!run)return;paused=true;touch.active=false;saveActive(level);$('pause').classList.remove('hidden')};$('resumeBtn').onclick=()=>{paused=false;$('pause').classList.add('hidden');last=performance.now()};$('restartBtn').onclick=()=>{score=checkpoint.score;coins=checkpoint.coins;gems=checkpoint.gems;lives=Math.max(1,checkpoint.lives);enterLevel(level,true)};$('quitBtn').onclick=goHome;$('againBtn').onclick=()=>{score=checkpoint.score;coins=checkpoint.coins;gems=checkpoint.gems;lives=Math.max(3,checkpoint.lives);enterLevel(level,true)};$('resultHomeBtn').onclick=goHome;$('nextBtn').onclick=()=>enterLevel(level+1,true);
window.addEventListener('keydown',e=>{if(!run||paused)return;if(e.key==='ArrowUp'||e.key===' '){e.preventDefault();jump()}if(e.key==='ArrowLeft'){touch.active=true;touch.dir=-1;touch.started=performance.now()}if(e.key==='ArrowRight'){touch.active=true;touch.dir=1;touch.started=performance.now()}});window.addEventListener('keyup',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){touch.active=false;touch.dir=0}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){if(run||activeRun)saveActive(level);syncScore(true)}});window.addEventListener('pagehide',()=>{if(run||activeRun)saveActive(level);syncScore(true)});
renderHome();generateLevel(1);updateHud();run=false;
})();