(()=>{
const c=document.getElementById('game'),x=c.getContext('2d'),app=document.getElementById('app');
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a);
const launch=new URLSearchParams(location.search).get('launch'),scoreApi='https://blockrush-backend.vercel.app/api/score';
const STAGES=[
 {name:'Thorncoil',sub:'Forest Serpent',a:'#7d35d8',b:'#f0a92e'},
 {name:'Emberfang',sub:'Volcanic Wyrm',a:'#e8443e',b:'#ffad32'},
 {name:'Frostmaw',sub:'Glacier Devourer',a:'#3f8cff',b:'#c8f6ff'},
 {name:'Venomspire',sub:'Toxic Basilisk',a:'#48c94f',b:'#b7f24b'},
 {name:'Stormscale',sub:'Thunder Serpent',a:'#5947db',b:'#63e7ff'},
 {name:'Duskreaver',sub:'Shadow Wyrm',a:'#61267b',b:'#e45bd9'},
 {name:'Suncrusher',sub:'Golden Colossus',a:'#ef9a24',b:'#fff06a'},
 {name:'Voidcoil',sub:'Abyssal Tyrant',a:'#3d155f',b:'#ac38ff'}
];
let profile=JSON.parse(localStorage.getItem('srrProfile')||'null')||{bankCoins:0,bankGems:0,bestStage:1,attackLv:1,critLv:1,skillLv:1,sound:true};
let selectedStage=Math.min(profile.bestStage,STAGES.length),stage=selectedStage,W=390,H=844,dpr=1,last=0,run=0,pause=0,shake=0;
let player,seg=[],bul=[],fx=[],float=[],haz=[],dead=0,total=34,coins=0,gems=0,combo=0,comboT=0,nextUp=0,shotT=0,shotRate=.28,dmg=72,split=1,crit=.12,critM=2,poison=0,spirit=0,bomb=0;
let cd={bomb:0,toxic:0,spirit:0,split:0};const marks=[.25,.5,.75],baseCd={bomb:7,toxic:8,spirit:6,split:10};
let audio=null;
function save(){localStorage.setItem('srrProfile',JSON.stringify(profile));renderHome()}
function beep(freq=440,dur=.05,type='sine',gain=.025){if(!profile.sound)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}catch(e){}}
function resize(){const r=app.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);c.width=r.width*dpr;c.height=r.height*dpr;W=r.width;H=r.height;x.setTransform(dpr,0,0,dpr,0,0);if(player)player.y=H-120}addEventListener('resize',resize);resize();
function path(t){const y=118+(H-365)*t,amp=Math.min(W*.31,145),px=W/2+Math.sin(t*Math.PI*5.25)*amp*(.76+.24*Math.sin(t*Math.PI));return{x:clamp(px,42,W-42),y}}
function alive(){return seg.filter(s=>!s.dead)}function front(){const a=alive();return a[a.length-1]||null}
function power(){return Math.round((dmg*split/shotRate)*(1+crit*(critM-1)))}
function reset(){seg=[];bul=[];fx=[];float=[];haz=[];dead=coins=gems=combo=nextUp=shotT=0;const skillScale=1+(profile.skillLv-1)*.06;shotRate=.28;dmg=72*(1+(profile.attackLv-1)*.12);split=1;crit=.12+(profile.critLv-1)*.018;critM=2;poison=spirit=bomb=0;cd={bomb:0,toxic:0,spirit:0,split:0};player={x:W/2,y:H-120};for(let i=0;i<total;i++){const hp=(820+Math.floor(i/5)*150+stage*150)*Math.pow(1.08,stage-1),isChest=[8,19,28].includes(i);seg.push({i,t:i/total*.9,hp:isChest?hp*.55:hp,max:isChest?hp*.55:hp,dead:0,isChest,flash:0})}Object.keys(baseCd).forEach(k=>baseCd[k]=baseCd[k]);hud();$('powerValue').textContent=(power()/1000).toFixed(2)+'K'}
function hud(){const p=dead/total;$('progressFill').style.width=(p*100)+'%';$('progressLabel').textContent=Math.round(p*100)+'%';$('coins').textContent=coins;$('gems').textContent=gems}
function burst(px,py,n,col){for(let i=0;i<n;i++)fx.push({x:px,y:py,vx:rand(-140,140),vy:rand(-170,70),life:rand(.35,.85),r:rand(2,6),col})}
function hit(s,amount,px,py){if(!s||s.dead)return;const cr=Math.random()<crit;if(cr)amount*=critM;s.hp-=amount;s.flash=.08;float.push({x:px,y:py,text:Math.round(amount)+(cr?'!':''),life:.7,vy:-38,cr});if(Math.random()<.07)beep(cr?760:520,.025,'square',.01);if(s.hp<=0){s.dead=1;dead++;combo++;comboT=2.2;coins+=s.isChest?95:18;if(s.isChest)gems+=3;shake=s.isChest?8:3;burst(px,py,s.isChest?24:10,s.isChest?'#ffd83d':STAGES[stage-1].a);beep(s.isChest?880:620,.06,'triangle',.02);hud();document.querySelector('#combo span').textContent=combo;$('combo').classList.add('show');const p=dead/total;if(nextUp<marks.length&&p>=marks[nextUp]){nextUp++;setTimeout(showUpgrade,220)}if(dead>=total)setTimeout(victory,450)}}
function shoot(){const s=front();if(!s)return;const p=path(s.t),a=Math.atan2(p.y-player.y,p.x-player.x);for(let i=0;i<split;i++){const sp=(i-(split-1)/2)*.075;bul.push({x:player.x,y:player.y-14,vx:Math.cos(a+sp)*540,vy:Math.sin(a+sp)*540,life:1.5,d:dmg})}}
function showUpgrade(){pause=1;const pool=[
 ['🏹','Split Arrow','Arrow split +1','SR',()=>split=Math.min(6,split+1)],['⚡','Rapid Volley','Attack speed +18%','R',()=>shotRate=Math.max(.105,shotRate*.82)],['🎯','Predator Focus','Critical chance +10%','SR',()=>crit=Math.min(.7,crit+.1)],['💥','Heavy Draw','Arrow damage +30%','SR',()=>dmg*=1.3],['🟣','Evil Spirit','Shadow Orb damage +45%','SR',()=>spirit++],['🧪','Venom Mastery','Poison damage +50%','R',()=>poison++],['💣','Royal Arsenal','Bomb damage +50%','SSR',()=>bomb++],['💫','Critical Fury','Critical damage +75%','SSR',()=>critM+=.75]
 ].sort(()=>Math.random()-.5).slice(0,3);const box=$('cards');box.innerHTML='';pool.forEach(o=>{const b=document.createElement('button');b.className='card';b.innerHTML=`<span class="icon">${o[0]}</span><span><b>${o[1]}</b><small>${o[2]}</small></span><span class="rarity">${o[3]}</span>`;b.onclick=()=>{o[4]();$('upgrade').classList.add('hidden');pause=0;$('powerValue').textContent=(power()/1000).toFixed(2)+'K';beep(700,.08,'sine',.03);last=performance.now()};box.appendChild(b)});$('upgrade').classList.remove('hidden')}
function cooldownMax(k){return baseCd[k]*Math.max(.55,1-(profile.skillLv-1)*.045)}
function skill(k){if(!run||pause||cd[k]>0)return;cd[k]=cooldownMax(k);const a=alive();if(!a.length)return;beep(k==='bomb'?150:k==='spirit'?280:420,.08,'sawtooth',.03);if(k==='bomb'){const t=front(),p=path(t.t);burst(p.x,p.y,35,'#ffd83d');a.slice(-6).forEach(s=>{const q=path(s.t);hit(s,360*(1+bomb*.5),q.x,q.y)})}if(k==='toxic'){const p=path(front().t);haz.push({x:p.x,y:p.y,r:90,life:4.2,tick:0});poison=Math.max(poison,1)}if(k==='spirit'){a.slice(-8).forEach(s=>{const q=path(s.t);hit(s,225*(1+spirit*.45),q.x,q.y)})}if(k==='split'){const old=split;split=Math.min(8,split+3);setTimeout(()=>split=old,4500)}}
document.querySelectorAll('.skill').forEach(b=>b.addEventListener('pointerdown',()=>skill(b.dataset.skill)));
function submit(sc){if(!launch)return;fetch(scoreApi,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({launch,score:Math.floor(sc)})}).catch(()=>{})}
function update(dt){comboT-=dt;if(comboT<=0){combo=0;$('combo').classList.remove('show')}Object.keys(cd).forEach(k=>cd[k]=Math.max(0,cd[k]-dt));document.querySelectorAll('.skill').forEach(b=>{const k=b.dataset.skill,m=cooldownMax(k),v=cd[k];b.querySelector('i').style.transform=`scaleX(${1-v/m})`;b.classList.toggle('ready',v===0)});shotT-=dt;if(shotT<=0){shoot();shotT=shotRate}seg.forEach(s=>{if(!s.dead){s.t+=dt*(.0135+stage*.00035);s.flash=Math.max(0,s.flash-dt)}});for(let i=bul.length-1;i>=0;i--){const b=bul[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let h=0;for(const s of alive().reverse()){const p=path(s.t);if((b.x-p.x)**2+(b.y-p.y)**2<700){hit(s,b.d,p.x,p.y);h=1;break}}if(h||b.life<=0||b.x<0||b.x>W||b.y<70||b.y>H)bul.splice(i,1)}for(let i=haz.length-1;i>=0;i--){const h=haz[i];h.life-=dt;h.tick-=dt;if(h.tick<=0){h.tick=.43;alive().slice(-10).forEach(s=>{const p=path(s.t);if((p.x-h.x)**2+(p.y-h.y)**2<h.r*h.r)hit(s,58*(1+poison*.5),p.x,p.y)})}if(h.life<=0)haz.splice(i,1)}for(let i=fx.length-1;i>=0;i--){const p=fx[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=240*dt;p.life-=dt;if(p.life<=0)fx.splice(i,1)}for(let i=float.length-1;i>=0;i--){const f=float[i];f.y+=f.vy*dt;f.life-=dt;if(f.life<=0)float.splice(i,1)}const f=front();if(f&&path(f.t).y>player.y-65){fail()}}
function drawHead(p,s){const col=STAGES[stage-1];x.save();x.translate(p.x,p.y);x.shadowColor=col.a;x.shadowBlur=18;x.fillStyle=col.a;x.beginPath();x.ellipse(0,0,34,28,0,0,Math.PI*2);x.fill();x.fillStyle=col.b;x.beginPath();x.moveTo(-22,-18);x.lineTo(-7,-42);x.lineTo(0,-21);x.lineTo(9,-45);x.lineTo(23,-18);x.fill();x.fillStyle='#ffe75f';x.beginPath();x.arc(-11,-4,5,0,Math.PI*2);x.arc(11,-4,5,0,Math.PI*2);x.fill();x.fillStyle='#130818';x.beginPath();x.arc(-11,-4,2,0,Math.PI*2);x.arc(11,-4,2,0,Math.PI*2);x.fill();x.fillStyle='#190c1d';x.beginPath();x.arc(0,10,12,0,Math.PI);x.fill();x.restore()}
function drawSegment(s,isFront){const p=path(s.t),col=STAGES[stage-1];if(isFront&&!s.isChest){drawHead(p,s)}else{x.save();x.translate(p.x,p.y);x.shadowColor=s.isChest?'#ffd83d':col.a;x.shadowBlur=s.flash?25:9;if(s.isChest){x.fillStyle='#6c3b17';x.fillRect(-22,-18,44,36);x.fillStyle='#f0b72b';x.fillRect(-20,-5,40,8);x.fillRect(-4,-18,8,36)}else{x.fillStyle=s.i%2?col.a:col.b;x.beginPath();x.ellipse(0,0,27,21,0,0,Math.PI*2);x.fill();x.fillStyle='#f7e6c4';for(const a of[-18,0,18]){x.beginPath();x.moveTo(a,-14);x.lineTo(a+6,-30);x.lineTo(a+12,-12);x.fill()}}x.restore()}x.fillStyle='#fff';x.font='bold 11px Arial';x.textAlign='center';x.shadowColor='#000';x.shadowBlur=4;x.fillText(s.isChest?'CHEST':Math.max(0,Math.ceil(s.hp)),p.x,p.y+4);x.shadowBlur=0}
function draw(){x.save();if(shake>0){x.translate(rand(-shake,shake),rand(-shake,shake));shake*=.82;if(shake<.3)shake=0}const col=STAGES[stage-1];let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,stage===3?'#88bff5':'#4aa9de');g.addColorStop(.47,stage===2?'#9b694c':'#7ecb75');g.addColorStop(1,'#33452f');x.fillStyle=g;x.fillRect(0,0,W,H);x.globalAlpha=.13;x.fillStyle=col.a;for(let i=0;i<10;i++){x.beginPath();x.arc((i*83+30)%W,120+(i*131)%(H-260),24+(i%4)*11,0,Math.PI*2);x.fill()}x.globalAlpha=1;x.fillStyle='#6e7655';x.fillRect(0,H-92,W,92);const f=front();[...seg].reverse().forEach(s=>{if(!s.dead)drawSegment(s,s===f)});for(const b of bul){x.strokeStyle='#d9fbff';x.lineWidth=3;x.shadowColor='#5edcff';x.shadowBlur=8;x.beginPath();x.moveTo(b.x,b.y);x.lineTo(b.x-b.vx*.026,b.y-b.vy*.026);x.stroke();x.shadowBlur=0}for(const h of haz){x.fillStyle='#66ff8844';x.beginPath();x.arc(h.x,h.y,h.r,0,Math.PI*2);x.fill()}for(const p of fx){x.globalAlpha=Math.max(0,p.life);x.fillStyle=p.col;x.beginPath();x.arc(p.x,p.y,p.r,0,Math.PI*2);x.fill()}x.globalAlpha=1;for(const f1 of float){x.fillStyle=f1.cr?'#ffd64a':'#fff';x.font='bold 18px Arial';x.textAlign='center';x.fillText(f1.text,f1.x,f1.y)}x.save();x.translate(player?.x||W/2,player?.y||H-120);x.shadowColor='#42d8ff';x.shadowBlur=15;x.fillStyle='#1e7148';x.beginPath();x.arc(0,0,18,0,Math.PI*2);x.fill();x.shadowBlur=0;x.fillStyle='#f4c56f';x.beginPath();x.arc(0,-15,8,0,Math.PI*2);x.fill();x.strokeStyle='#7be7ff';x.lineWidth=3;x.beginPath();x.arc(0,-4,22,-1.2,1.2);x.stroke();x.restore();x.restore()}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;if(run&&!pause)update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function setX(px){const r=c.getBoundingClientRect();player.x=clamp(px-r.left,28,W-28)}let drag=0;c.addEventListener('pointerdown',e=>{if(!run)return;drag=1;setX(e.clientX)});c.addEventListener('pointermove',e=>{if(drag)setX(e.clientX)});addEventListener('pointerup',()=>drag=0);
function start(){stage=selectedStage;reset();run=1;pause=0;$('home').classList.add('hidden');$('result').classList.add('hidden');$('hud').classList.remove('hidden');$('skills').classList.remove('hidden');$('stageLabel').textContent=`Stage ${stage} · ${STAGES[stage-1].name}`;last=performance.now();beep(360,.12,'triangle',.03)}
function scoreNow(){return stage*10000+coins+gems*30+dead*120+Math.round(combo*25)}
function fail(){if(!run)return;run=0;pause=1;beep(110,.25,'sawtooth',.04);document.querySelector('#result .ribbon').textContent='RAID FAILED';$('resultTitle').textContent='The serpent broke through';$('rewardCoins').textContent=coins;$('rewardGems').textContent=gems;$('rewardShards').textContent=0;$('scoreReward').textContent=scoreNow();$('nextBtn').classList.add('hidden');$('result').classList.remove('hidden');submit(scoreNow())}
function victory(){if(!run)return;run=0;pause=1;const bonusCoins=700+stage*150,bonusGems=18+stage*3,earnedCoins=coins+bonusCoins,earnedGems=gems+bonusGems;profile.bankCoins+=earnedCoins;profile.bankGems+=earnedGems;if(stage===profile.bestStage&&profile.bestStage<STAGES.length)profile.bestStage++;save();beep(880,.12,'triangle',.04);setTimeout(()=>beep(1170,.16,'triangle',.035),120);document.querySelector('#result .ribbon').textContent='VICTORY!';$('resultTitle').textContent=`${STAGES[stage-1].name} defeated`;$('rewardCoins').textContent=earnedCoins;$('rewardGems').textContent=earnedGems;$('rewardShards').textContent=1+Math.floor(stage/2);$('scoreReward').textContent=scoreNow();$('nextBtn').classList.toggle('hidden',stage>=STAGES.length);$('result').classList.remove('hidden');submit(scoreNow());try{TelegramGameProxy?.shareScore()}catch(e){}}
function renderHome(){selectedStage=Math.min(selectedStage,profile.bestStage,STAGES.length);const st=STAGES[selectedStage-1];$('bankCoins').textContent=profile.bankCoins;$('bankGems').textContent=profile.bankGems;$('bestStage').textContent=profile.bestStage;$('selectedStage').textContent=`Stage ${selectedStage}`;$('homeStageName').textContent=st.name;$('homeStageText').textContent=`Stage ${selectedStage} · ${st.sub}`;$('attackLv').textContent=`Lv ${profile.attackLv}`;$('critLv').textContent=`Lv ${profile.critLv}`;$('skillLv').textContent=`Lv ${profile.skillLv}`;$('attackCost').textContent=`${200*profile.attackLv} 🪙`;$('critCost').textContent=`${250*profile.critLv} 🪙`;$('skillCost').textContent=`${8+profile.skillLv*2} 💎`;$('soundBtn').textContent=profile.sound?'🔊 Sound On':'🔇 Sound Off'}
function goHome(){run=0;pause=0;$('result').classList.add('hidden');$('hud').classList.add('hidden');$('skills').classList.add('hidden');$('home').classList.remove('hidden');renderHome()}
$('playBtn').onclick=start;$('restartBtn').onclick=start;$('homeBtn').onclick=goHome;$('nextBtn').onclick=()=>{selectedStage=Math.min(STAGES.length,Math.max(selectedStage+1,stage+1),profile.bestStage);start()};$('prevStage').onclick=()=>{selectedStage=Math.max(1,selectedStage-1);renderHome();beep(260,.04)};$('nextStagePick').onclick=()=>{selectedStage=Math.min(profile.bestStage,STAGES.length,selectedStage+1);renderHome();beep(340,.04)};$('upgradeBtn').onclick=()=>{$('meta').classList.remove('hidden');renderHome()};$('closeMeta').onclick=()=>$('meta').classList.add('hidden');$('soundBtn').onclick=()=>{profile.sound=!profile.sound;save();if(profile.sound)beep(620,.07)};
document.querySelectorAll('.meta-up').forEach(b=>b.onclick=()=>{const k=b.dataset.up;if(k==='attack'){const cost=200*profile.attackLv;if(profile.bankCoins<cost)return beep(120,.08,'square',.03);profile.bankCoins-=cost;profile.attackLv++}if(k==='crit'){const cost=250*profile.critLv;if(profile.bankCoins<cost)return beep(120,.08,'square',.03);profile.bankCoins-=cost;profile.critLv++}if(k==='skill'){const cost=8+profile.skillLv*2;if(profile.bankGems<cost)return beep(120,.08,'square',.03);profile.bankGems-=cost;profile.skillLv++}save();beep(760,.08,'triangle',.03)});
renderHome();reset();
})();